package com.sobu.baseapplication.utils

object SharePreference {
     const val billingRequireKey = "isAppPurchased"
     const val isShowFirstScreenKey = "showFirstScreen"
     const val firstTimeAskingPermission = "firstTimeAskingPermission"
     const val selectedLanguageCodeKey = "selectedLanguageCode"
     const val backgroundUriKey = "backgroundUriKey"
     const val isTurnOnRecordSoundKey = "isTurnOnRecordSoundKey"
     const val isTrackingCoughKey = "isTrackingCoughKey"
     const val isTrackingCryKey = "isTrackingCryKey"
     const val isTrackingSnoreKey = "isTrackingSnoreKey"
     const val isTrackingFluKey = "isTrackingFluKey"
     const val isTrackingSmileKey = "isTrackingSmileKey"
     const val isNotificationRemindKey = "isNotificationRemindKey"

     const val isTrackingCHILD_SPEECHKey = "isTrackingCHILD_SPEECHKey"
     const val isTrackingBABBLINGKey = "isTrackingBABBLINGKey"
     const val isTrackingSHOUTKey = "isTrackingSHOUTKey"
     const val isTrackingYELLKey = "isTrackingYELLKey"
     const val isTrackingCHILDREN_SHOUTKey = "isTrackingCHILDREN_SHOUTKey"
     const val isTrackingSCREAMINGKey = "isTrackingSCREAMINGKey"
     const val isTrackingLAUGHTERKey = "isTrackingLAUGHTERKey"
     const val isTrackingBABY_LAUGHTERKey = "isTrackingBABY_LAUGHTERKey"
     const val isTrackingGIGGLEKey = "isTrackingGIGGLEKey"
     const val isTrackingSNICKERKey = "isTrackingSNICKERKey"
     const val isTrackingBELLY_LAUGHKey = "isTrackingBELLY_LAUGHKey"
     const val isTrackingCHUCKLE_CHORTLEKey = "isTrackingCHUCKLE_CHORTLEKey"
     const val isTrackingCRYING_SOBBINGKey = "isTrackingCRYING_SOBBINGKey"
     const val isTrackingBABY_INFANT_CRYKey = "isTrackingBABY_INFANT_CRYKey"
     const val isTrackingWHIMPERKey = "isTrackingWHIMPERKey"
     const val isTrackingWAIL_MOANKey = "isTrackingWAIL_MOANKey"
     const val isTrackingCHILD_SINGINGKey = "isTrackingCHILD_SINGINGKey"
     const val isTrackingWHEEZEKey = "isTrackingWHEEZEKey"
     const val isTrackingSNORINGKey = "isTrackingSNORINGKey"
     const val isTrackingGASPKey = "isTrackingGASPKey"
     const val isTrackingPANTKey = "isTrackingPANTKey"
     const val isTrackingSNORTKey = "isTrackingSNORTKey"
     const val isTrackingCOUGHKey = "isTrackingCOUGHKey"
     const val isTrackingSNEEZEKey = "isTrackingSNEEZEKey"
     const val isTrackingSNIFFKey = "isTrackingSNIFFKey"
     const val isTrackingCHEWINGKey = "isTrackingCHEWINGKey"
     const val isTrackingBURPINGKey = "isTrackingBURPINGKey"
     const val isTrackingHICCUPKey = "isTrackingHICCUPKey"
     const val isTrackingFARTKey = "isTrackingFARTKey"
     const val isTrackingCHILDREN_PLAYINGKey = "isTrackingCHILDREN_PLAYINGKey"
}